services:
  server:
    image: osixia/phpldapadmin:0.9.0
    restart: unless-stopped
    volumes:
      - ./data/logs:/var/www/html/storage/logs
      - ./data/sessions:/var/www/html/storage/framework/sessions
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldapserver
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    ports:
      - ${PHPLDAPADMIN_PORT:-80}:80
    extra_hosts:
      - "ldap=${PHPLDAPADMIN_LDAP_HOST}"
